name: Build Armbian for XF.A311D2

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'  # 每周日凌晨2点自动构建
  workflow_dispatch:  # 手动触发
    inputs:
      release_type:
        description: 'Build type'
        required: true
        default: 'bookworm'
        type: choice
        options:
        - bookworm
        - bullseye
      desktop:
        description: 'Include desktop'
        required: true
        default: 'yes'
        type: choice
        options:
        - yes
        - no

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    
    strategy:
      matrix:
        include:
          - build_type: xfce-desktop
            desktop: yes
            release: bookworm
          - build_type: minimal
            desktop: no  
            release: bookworm

    steps:
    - name: Checkout custom config
      uses: actions/checkout@v4
      with:
        path: custom-config

    - name: Checkout Armbian build system
      uses: actions/checkout@v4
      with:
        repository: armbian/build
        path: build
        ref: main

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential ccache cmake cpio curl \
          device-tree-compiler dialog dirmngr dosfstools fakeroot \
          flex gawk git gnupg gperf libelf-dev liblz4-tool \
          libncurses5-dev libsdl2-dev libssl-dev lsb-release \
          lzop mtools ninja-build openssh-client pkg-config \
          python3 python3-pip rsync snapd sudo systemd-container \
          u-boot-tools udev unzip vim wget xz-utils zip zlib1g-dev

    - name: Copy custom configurations
      run: |
        cp -r custom-config/config/* build/config/
        cp -r custom-config/patches/* build/patches/ 2>/dev/null || true
        cp -r custom-config/scripts/* build/userpatches/ 2>/dev/null || true
        chmod +x build/userpatches/*.sh 2>/dev/null || true

    - name: Build Armbian Image
      run: |
        cd build
        ./compile.sh \
          BOARD=xf-a311d2 \
          BRANCH=edge \
          RELEASE=${{ matrix.release }} \
          BUILD_DESKTOP=${{ matrix.desktop }} \
          DESKTOP_ENVIRONMENT=xfce \
          KERNEL_CONFIGURE=yes \
          BUILD_MINIMAL=no \
          EXPERT=yes \
          BSPFREEZE=yes

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armbian-${{ matrix.build_type }}-${{ github.sha }}
        path: |
          build/output/images/*.img
          build/output/images/*.txt
          build/output/images/*.md5
        retention-days: 30
        compression-level: 0

    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/output/images/*.img
        body: |
          Custom Armbian for XF.A311D2 Board
          - Build date: ${{ github.event.head_commit.timestamp }}
          - Commit: ${{ github.sha }}
          - Type: ${{ matrix.build_type }}
